### ISSUE TITLE
us_get_info.py::Line38:: symbols, msg = usstock.get_symbols() does not work 

### ISSUE THREAD

**Issue by moonmonk14134** [bankrollhunter/market-breadth#5]
@hk-Lei   opendatatools.usstock.get_symbols()  seems not work anymore due to yahoo.
1. could you verify?
2. if opendatatools.usstock.get_symbols() not work, any alternative.

thank you.
moonmonk

**Comment by MARGI3** [comment]
@moonmonk14134 

here is my solution, hope this will help you.

[OpenDataTools issue](https://github.com/PKUJohnson/OpenData/issues/35)

[StackOverflow](https://stackoverflow.com/a/25339061/4593755)

you should replace the US market url which is used by opendatatools

File "/usr/local/lib/python3.7/site-packages/opendatatools/usstock/usstock_agent.py", line 29

```
url = 'https://old.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange=%s&render=download' % market
```

**Comment by moonmonk14134** [comment]
@MARGI3  it works. Thank you 👍

**Comment by wh5231** [comment]
Traceback (most recent call last):
  File "task/us_get_info.py", line 38, in <module>
    symbols, msg = usstock.get_symbols()
  File "D:\Program Files (x86)\anaconda\lib\site-packages\opendatatools\usstock\usstock_interface.py", line 11, in get_symbols
    return usstock_agent.get_symbols()
  File "D:\Program Files (x86)\anaconda\lib\site-packages\opendatatools\usstock\usstock_agent.py", line 37, in get_symbols
    df_nasdaq = self._get_symbols('nasdaq')
  File "D:\Program Files (x86)\anaconda\lib\site-packages\opendatatools\usstock\usstock_agent.py", line 30, in _get_symbols
    response = self.do_request(url, None, method='GET', type='binary')
  File "D:\Program Files (x86)\anaconda\lib\site-packages\opendatatools\common\rest_agent.py", line 32, in do_request
    res = self.session.get(url, params=param, **kwargs)
  File "D:\Program Files (x86)\anaconda\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "D:\Program Files (x86)\anaconda\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Program Files (x86)\anaconda\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "D:\Program Files (x86)\anaconda\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='old.nasdaq.com', port=443): Max retries exceeded with url: /screening/companies-by-name.aspx?letter=0&exchan
ge=nasdaq&render=download (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

**Comment by hk-Lei** [comment]
把 opendatatools 换成这个吧： https://github.com/hk-Lei/OpenData
