### ISSUE TITLE
zh_get_daily.py 报错

### ISSUE THREAD

**Issue by onlytiancai** [bankrollhunter/market-breadth#7]
$ python3.6 task/zh_get_daily.py
清空表数据：
                TRUNCATE TABLE zh_stocks_d;

processing [1/4056] : 000001.SZ
Traceback (most recent call last):
  File "task/zh_get_daily.py", line 59, in <module>
    df = analysis.stock_zh_analysis(df, 20, 60, 120)
  File "task/../tools/util/analysis.py", line 164, in stock_zh_analysis
    data = stock_gap_and_over(data)
  File "task/../tools/util/analysis.py", line 91, in stock_gap_and_over
    axis=1, raw=True)
  File "/home/wawa/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 7552, in apply
    return op.get_result()
  File "/home/wawa/.local/lib/python3.6/site-packages/pandas/core/apply.py", line 178, in get_result
    return self.apply_raw()
  File "/home/wawa/.local/lib/python3.6/site-packages/pandas/core/apply.py", line 235, in apply_raw
    result = np.apply_along_axis(wrap_function(self.f), self.axis, self.values)
  File "<__array_function__ internals>", line 6, in apply_along_axis
  File "/home/wawa/.local/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 379, in apply_along_axis
    res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
  File "/home/wawa/.local/lib/python3.6/site-packages/pandas/core/apply.py", line 228, in wrapper
    result = func(*args, **kwargs)
  File "task/../tools/util/analysis.py", line 90, in <lambda>
    lambda row: is_gap(row['high'], row['low'], row['close'], row['pre_high'], row['pre_low'], row['pre_close']),
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by hk-Lei** [comment]
pandas 的版本使用 0.25.3 试试
